### ISSUE TITLE
Component does not update

### ISSUE THREAD

**Issue by gabrielHosino** [tan31989/react-radio-button#1]
Hi, I don't really know if i made a mistake(I'm quite new to react) or if it's really a bug. I have a function that gives me the optionsList to the radioButtonGroup like: 

```javascript
renderOptions(data){
    data.map(year => {
          if(this.props.graphicControl){
            option['value'] = year.toString()
            option['text'] = year.toString()
            radioYearsOptions.push(option)
            option = {}
          }else{
            if(parseInt(year, 10) >= parseInt(this.props.yearBegin,10)){
              option['value'] = year.toString()
              option['text'] = year.toString()
              radioYearsOptions.push(option)
              option = {}
            }
          }
        })
      return radioYearsOptions
}
```

Where **data** is a props that the parent component receive from the store(redux), when that props is updated the parent component re-render but the radioButtonGroup does not. I can see that the parent component updated because the value returned by that function changes.
Can you help me?
Thank you

**Comment by gabrielHosino** [comment]
I think i figured it out, you are using a variable instead of the props for the list of options, since the component is already mounted, it does not pass again through the constructor when you change the props, then although the component re-renders the options stays the same. 

I think it's a easy thing to correct, if you don't have the time i could help you with that. 

Thank you!

**Comment by ntantri** [comment]
Hi @gabrielHosino,

Apologies for the delay in reply.
I was not available for that.

If you can provide a PR, let me know.

Regards,
Nagaraj

**Comment by gabrielHosino** [comment]
Thanks for the reply! I created a PR for this issue.
